### ISSUE TITLE
CUDA OOM when using Surya on only 5 images!

### ISSUE THREAD

**Issue by benhachy** [VikParuchuri/surya#62]
Hi! 

As mentionned in the README section, the **RECOGNITION_BATCH_SIZE** is by default set to **256**, as each batch item would occupy **50 mb** in GPU VRAM. However, after only using Surya OCR on **4 images**, the occupied GPU Memory is **15 GB**, as shown below:

![image](https://github.com/VikParuchuri/surya/assets/74056452/bf670217-c8b7-4e86-9633-355fc588e1e2)

And as soon as I use **5 images** I get an **OOM**. I find this quite different from what was said on the readme which gives the impression that we can set the  **RECOGNITION_BATCH_SIZE** very high.

I have also a question, how did you derive the calculation of **50mb per batch item** in the readme?

I would appreciate any help! Thanks!

**Comment by benhachy** [comment]
# Problem Solved 🛠️

The GPU memory needed for inference depends greatly on the number of lines in the image. In my case, I had an image which was a big table, and each cell was detected as a box. Consequently, I had 500 bounding boxes (bboxes) which resulted in the Cuda Out Of Memory (OOM) Error. 💥

Here are the results of a statistical analysis I have done:

![Statistical Analysis](https://github.com/VikParuchuri/surya/assets/74056452/c81b9a45-aaf5-4b21-a6b8-df2c234e74e0)

We can see that there is a linear relationship between the number of lines and the GPU memory needed for inference. After training an Ordinary Least Squares (OLS) model, I would suggest the following thresholds to avoid an OOM error:

- For a **T4 GPU (16 Gb in VRAM)**, the maximum threshold is approximately **428 lines (bboxes more precisely)**.
- For an **A1000 (80 Gb in VRAM)**, the maximum threshold is approximately **2500 lines**.

Please note that for each line (bbox) added in an image, an additional **30 mb of GPU memory is required**.

![GPU Memory Requirement](https://github.com/VikParuchuri/surya/assets/74056452/cf88dde7-704d-4f83-a711-a16c50997386)

I hope this information will be useful for future users! 🚀

**Comment by kurkurzz** [comment]
Is there a way to configure this such a way that it would not throw CUDA OOM? longer processing is fine, as long as it can be processed with any VRAM size.

**Comment by Madiwka4** [comment]
Would there be a way to make one big bounding box? I don't really want them, I just want the OCR'ed text

**Comment by benhachy** [comment]
@Madiwka4 , using a single large bounding box isn’t feasible because Surya’s workflow involves first detecting individual text lines with bounding boxes. Each detected text line is then passed to the Surya text recognition model for processing. This text detection step is essential and cannot be bypassed by using one big bounding box. I hope this explanation makes it clearer!

**Comment by ZEROdcFRAME** [comment]
@benhachy 
Thanks for sharing the information.

I am running the function `run_ocr(images, image_langs, det_model, det_processor, rec_model, rec_processor)` in python.
I looked in `surya/settgins.py` and could not find the variable that sets the bbox threashold.

Can you share a code snippet in this thread to show me where I should change it?

**Comment by irfannaqieb** [comment]
> Is there a way to configure this such a way that it would not throw CUDA OOM? longer processing is fine, as long as it can be processed with any VRAM size.

continuing on this, if you are using lower end GPUs with lower VRAMs, lowering the `RECOGNITION_BATCH_SIZE` in `settings.py` solved the OOM issue in my case (default value is 256)
